- id: cp
  name: cp
  description: Copies files
  path: cp
  runtime: other

  parameters:
    - id: no_overwrite
      name: No overwrite
      description: Do not overwrite existing file
      type: input
      cardinality: 1..1
      label: -n
      dataType: boolean
      default: false

    - id: input_file
      name: Input file name
      description: Input file name
      type: input
      cardinality: 1..1
      dataType: file

    - id: output_file
      name: Output file name
      description: Output file name
      type: output
      cardinality: 1..1
      dataType: file

- id: sleep
  name: sleep
  description: sleeps for the given amount of seconds
  path: sleep
  runtime: other
  parameters:
    - id: seconds
      name: seconds to sleep
      description: The number of seconds to sleep
      type: input
      cardinality: 1..1
      dataType: integer

- id: docker_hello_world
  name: Docker hello world
  description: Runs the hello-world Docker image
  path: hello-world
  runtime: docker
  parameters: []

- id: kubernetes_hello_world
  name: Kubernetes hello world
  description: Runs the hello-world Docker image in a pod
  path: hello-world
  runtime: kubernetes
  parameters: []

- id: faas_hello_world
  name: FaaS hello world
  description: Runs a kotlin hello world inside a service
  path: "docker.io/klohrha/helloworld-kotlin"
  runtime: faas
  parameters: []

- id: kubernetes_testing
  name: Kubernetes testing
  description: Runs the nginx image
  path: nginx
  runtime: kubernetes
  parameters: []

- id: panorama-tiler
  name: panorama-tiler
  description: Generates panorama tiles to a directory
  path: "geocode.igd.fraunhofer.de:4567/telekom/panorama-tiler:v3.4.2"
  runtime: docker
  parameters:
    - id: input_directory
      name: Input directory
      description: A directory containing panoramas to convert
      type: input
      cardinality: 1..1
      dataType: directory
    - id: output_directory
      name: Output directory
      description: An output directory
      type: output
      cardinality: 1..1
      dataType: file

- id: panorama-tiler-kubernetes
  name: panorama-tiler-kubernetes
  description: Generates panorama tiles to a directory
  path: "geocode.igd.fraunhofer.de:4567/telekom/panorama-tiler:v3.4.2"
  runtime: kubernetes
  parameters:
    - id: input_directory
      name: Input directory
      description: A directory containing panoramas to convert
      type: input
      cardinality: 1..1
      dataType: directory
    - id: output_directory
      name: Output directory
      description: An output directory
      type: output
      cardinality: 1..1
      dataType: file

- id: panorama-tiler-faas
  name: panorama-tiler-faas
  description: Generates panorama tiles to a directory
  path: "geocode.igd.fraunhofer.de:4567/telekom/panorama-tiler:v3.4.2"
  runtime: faas
  parameters:
    - id: input_directory
      name: Input directory
      description: A directory containing panoramas to convert
      type: input
      cardinality: 1..1
      dataType: directory
    - id: output_directory
      name: Output directory
      description: An output directory
      type: output
      cardinality: 1..1
      dataType: file

- id: anonymizer
  name: anonymizer
  description: Anonymizes images from a directory and saves them to a directory
  path: "geocode.igd.fraunhofer.de:4567/hklohr/anonymizer"
  runtime: docker
  parameters:
    - id: input_directory
      name: Input directory
      description: A directory containing images to convert
      type: input
      cardinality: 1..1
      dataType: directory
      label: -i
    - id: output_directory
      name: Output directory
      description: An output directory
      type: output
      cardinality: 1..1
      dataType: file
      label: -o

- id: anonymizer-kubernetes
  name: anonymizer-kubernetes
  description: Anonymizes images from a directory and saves them to a directory
  path: "geocode.igd.fraunhofer.de:4567/hklohr/anonymizer"
  runtime: kubernetes
  parameters:
    - id: input_directory
      name: Input directory
      description: A directory containing images to convert
      type: input
      cardinality: 1..1
      dataType: directory
      label: -i
    - id: output_directory
      name: Output directory
      description: An output directory
      type: output
      cardinality: 1..1
      dataType: file
      label: -o

- id: docker_sleep
  name: Docker sleep
  description: Run sleep inside an alpine container
  path: alpine
  runtime: docker

  parameters:
    - id: sleep
      name: sleep command
      description: The sleep command
      type: input
      cardinality: 1..1
      dataType: string
      default: sleep

    - id: seconds
      name: seconds to sleep
      description: The number of seconds to sleep
      type: input
      cardinality: 1..1
      dataType: integer
